Repository epfml/disco, pull requests merged in 2022-04, with the labels that each got.

#273 Remove text
  mobile-browser-based-version/server/README.md
Labels: documentation

#274 Image training on Node.js
  mobile-browser-based-version/src/components/building_frames/containers/TrainingFrame.vue
  mobile-browser-based-version/src/core/dataset/data_loader/data_loader.ts
  mobile-browser-based-version/src/core/dataset/data_loader/image_loader.ts
  mobile-browser-based-version/src/core/dataset/data_loader/tabular_loader.ts
  mobile-browser-based-version/src/core/dataset/dataset_builder.ts
  mobile-browser-based-version/src/core/training/disco.ts
  mobile-browser-based-version/src/core/training/trainer/trainer.ts
  mobile-browser-based-version/tests/core/dataset/data_loader/image_loader.test.ts
  mobile-browser-based-version/tests/training_manager.test.ts
Labels: bug

#276 Batch image dataset & One-hot labels
  mobile-browser-based-version/src/components/building_frames/containers/TrainingFrame.vue
  mobile-browser-based-version/src/components/building_frames/image/ImageTrainingFrame.vue
  mobile-browser-based-version/src/components/building_frames/tabular/TabularTrainingFrame.vue
  mobile-browser-based-version/src/core/dataset/data_loader/data_loader.ts
  mobile-browser-based-version/src/core/dataset/data_loader/image_loader.ts
  mobile-browser-based-version/src/core/dataset/data_loader/tabular_loader.ts
  mobile-browser-based-version/src/core/dataset/dataset_builder.ts
  mobile-browser-based-version/src/core/training/disco.ts
  mobile-browser-based-version/src/core/training/trainer/trainer.ts
  mobile-browser-based-version/tests/core/dataset/data_loader/image_loader.test.ts
  mobile-browser-based-version/tests/core/dataset/data_loader/tabular_loader.test.ts
  mobile-browser-based-version/tests/training_manager.test.ts
Labels: bug

#297 UI fix and components reorder
  browser/src/components/App.vue
  browser/src/components/ModelActorFrame.vue
  browser/src/components/dataset_input/DatasetInputFrame.vue
  browser/src/components/dataset_input/FileSelectionFrame.vue
  browser/src/components/dataset_input/preview/PreviewGallery.vue
  browser/src/components/dataset_input/preview/data_types/ElementData.vue
  browser/src/components/dataset_input/preview/data_types/EmptyData.vue
  browser/src/components/dataset_input/preview/data_types/FileData.vue
  browser/src/components/dataset_input/preview/data_types/ImageData.vue
  browser/src/components/description/DescriptionFrame.vue
  browser/src/components/navigation/Navigation.vue
  browser/src/components/navigation/ProgressBar.vue
  browser/src/components/navigation/steps/DatasetInputStep.vue
  browser/src/components/navigation/steps/DescriptionStep.vue
  browser/src/components/navigation/steps/TestingStep.vue
  browser/src/components/navigation/steps/TrainingStep.vue
  browser/src/components/pages/Home.vue
  browser/src/components/pages/Information.vue
  browser/src/components/pages/NewTaskCreationForm.vue
  browser/src/components/pages/NotFound.vue
  browser/src/components/pages/TaskList.vue
  browser/src/components/testing/ImagePredictionResultsFrame.vue
  browser/src/components/testing/ImageTestingFrame.vue
  browser/src/components/testing/TabularTestingFrame.vue
  browser/src/components/testing/TestingFrame.vue
  browser/src/components/training/ImageTrainingFrame.vue
  browser/src/components/training/TabularTrainingFrame.vue
  browser/src/components/training/TrainingFrame.vue
  browser/src/components/training/TrainingInformationFrame.vue
  browser/src/router/index.ts
Labels: enhancement, user interface
