Repository epfml/disco, pull requests merged in 2022-06, with the labels that each got.

#322 Add testing component
  browser/src/components/App.vue
  browser/src/components/Description.vue
  browser/src/components/Finished.vue
  browser/src/components/ModelCaching.vue
  browser/src/components/containers/BaseLayout.vue
  browser/src/components/containers/ButtonCard.vue
  browser/src/components/containers/IconCard.vue
  browser/src/components/dataset_input/DatasetInput.vue
  browser/src/components/dataset_input/FileSelection.vue
  browser/src/components/navigation/Navigation.vue
  browser/src/components/navigation/ProgressBar.vue
  browser/src/components/navigation/ProgressIcon.vue
  browser/src/components/pages/Home.vue
  browser/src/components/pages/Information.vue
  browser/src/components/pages/NewTaskCreationForm.vue
  browser/src/components/pages/NotFound.vue
  browser/src/components/pages/TaskList.vue
  browser/src/components/sidebar/ModelLibrary.vue
  browser/src/components/sidebar/Settings.vue
  browser/src/components/testing/NewTesting.vue
  browser/src/components/testing/TestingBar.vue
  browser/src/components/testing/TestingFrame.vue
  browser/src/components/training/Training.vue
  browser/src/components/training/TrainingInformation.vue
  browser/src/components/unused/ImagePredictionResults.vue
  browser/src/components/unused/ImageTesting.vue
  browser/src/components/unused/ImageTraining.vue
  browser/src/components/unused/ModelActor.vue
  browser/src/components/unused/TabularTesting.vue
  browser/src/components/unused/TabularTraining.vue
  browser/src/main.ts
  browser/src/memory.ts
  browser/src/router/index.ts
  browser/src/shims-vuex.d.ts
  browser/src/store/index.ts
  browser/src/store/store.ts
Labels: bug, enhancement

#305 Fix README links
  browser/README.md
Labels: documentation

#328 UI: About Us page
  browser/src/assets/images/mlologo.png
  browser/src/assets/svg/AboutUsIcon.vue
  browser/src/components/pages/AboutUs.vue
  browser/src/components/sidebar/Sidebar.vue
  browser/src/router/index.ts
Labels: user interface

#334 Fix testing redirection & model library
  browser/src/components/Finished.vue
  browser/src/components/containers/IconCard.vue
  browser/src/components/pages/Features.vue
  browser/src/components/pages/Further.vue
  browser/src/components/pages/Home.vue
  browser/src/components/pages/Tutorial.vue
  browser/src/components/sidebar/ModelLibrary.vue
  browser/src/components/testing/NewTesting.vue
  browser/src/memory.ts
  browser/src/store/index.ts
  discojs/src/client/federated.ts
  discojs/src/memory/base.ts
  discojs/src/memory/empty.ts
Labels: bug

#341 Minor updates
  browser/public/index.html
  browser/src/assets/css/styles.css
  browser/src/assets/fonts/AmpleSoftMedium.woff
  browser/src/assets/fonts/AmpleSoftMedium.woff2
  browser/src/assets/gif/DecentralizedGIF.vue
  browser/src/assets/gif/DiscoGIF.vue
  browser/src/assets/gif/FederatedGIF.vue
  browser/src/assets/gif/raw/decentralized_render.gif
  browser/src/assets/gif/raw/discoWelcome500.gif
  browser/src/assets/gif/raw/federated_render.gif
  browser/src/assets/public/decentralized_rev2.gif
  browser/src/assets/public/federated_rev3.gif
  browser/src/components/pages/AboutUs.vue
  browser/src/components/pages/Home.vue
  browser/src/components/pages/Information.vue
  browser/src/components/pages/TaskList.vue
  browser/src/components/sidebar/Sidebar.vue
  browser/tailwind.config.js
  discojs/src/tasks/simple_face.ts
Labels: user interface

#344 UI: Update animated Disco logo
  browser/src/assets/gif/DiscoGIF.vue
  browser/src/assets/gif/raw/discoWelcome500.gif
  browser/src/assets/gif/raw/disco_middle.gif
  browser/src/components/pages/AboutUs.vue
  browser/src/components/pages/Home.vue
Labels: enhancement, user interface
