Repository epfml/disco, pull requests merged in 2024-05, with the labels that each got.

#659 Benchmark GPT-tfjs
  cli/README.md
  cli/package.json
  cli/src/benchmark_gpt.ts
  discojs/discojs-core/src/models/gpt/config.ts
  discojs/discojs-core/src/models/gpt/index.ts
  discojs/discojs-core/src/models/gpt/layers.ts
  discojs/discojs-core/src/models/gpt/model.ts
  discojs/discojs-core/src/models/model.ts
  discojs/discojs-core/src/models/tfjs.ts
  docs/examples/package.json
  docs/examples/wikitext.ts
  package-lock.json
Labels: documentation

#660 LUS COVID demo
  .gitignore
  cli/src/args.ts
  cli/src/cli.ts
  cli/src/data.ts
  datasets/.gitignore
  datasets/populate
  discojs/discojs-core/src/client/event_connection.ts
  discojs/discojs-core/src/dataset/data/image_data.ts
  discojs/discojs-core/src/dataset/data_loader/data_loader.ts
  discojs/discojs-core/src/dataset/data_loader/image_loader.ts
  discojs/discojs-core/src/dataset/dataset_builder.ts
  discojs/discojs-core/src/default_tasks/lus_covid.ts
  discojs/discojs-core/src/serialization/weights.ts
  discojs/discojs-core/src/training/disco.ts
  discojs/discojs-core/src/training/trainer/trainer_builder.ts
  discojs/discojs-node/src/data/image_loader.spec.ts
  discojs/discojs-node/src/data/image_loader.ts
  package-lock.json
  server/.gitignore
  server/src/router/federated/server.ts
  server/src/tasks.ts
  server/src/utils.ts
  server/tests/e2e/federated.spec.ts
  server/tests/validator.spec.ts
  web-client/package.json
  web-client/src/components/training/Trainer.vue
  web-client/src/components/training/TrainingInformation.vue
  web-client/src/components/training/__tests__/TrainingInformation.spec.ts
  web-client/src/store/memory.ts
  web-client/vite.config.ts
Labels: bug, discojs

#672 docker: freeze node version
  Dockerfile
Labels: bug
